# Generated by Django 4.0.3 on 2022-03-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=35)),
                ('p_image', models.ImageField(upload_to='')),
                ('p_descript', models.TextField(max_length=200)),
            ],
        ),
    ]
